fos_user:
    db_driver: orm
    firewall_name: main
    user_class: '%user_class%'
    from_email:
        address:        noreply@test.com
        sender_name:    "Test"
    registration:
        confirmation:
            enabled: false