security:

    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:

        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_register:
            pattern: ^/api/v1/register
            anonymous: true

        api:
            provider: fos_userbundle
            pattern: ^/api
            fos_oauth: true
            stateless: true
            anonymous: false

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        main:
            anonymous: true

    access_control:
